/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import lib.Joker;

public class JokerTest {
    @Test public void testJokerMethod() {
        Joker classUnderTest = new Joker();
        //change this to verify "Why is 6 afraid of 7?"
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.getJoke());
    }
}
